OOP school library - add basic UI : Pull Request
belaymit/oop_school_library pull request #4
Opened 2023-03-10 18:14 UTC by belaymit

## Description
**_In this project,_** I created a form of UI for my school library app. This way it can be invoked as an executable and not something I use in IRB exclusively.

## Project requirements

- Create a ``app.rb`` file that will serve as your console app entry-point. It should have methods that do the following:

- [ ]     List all books.
- [ ]     List all people.
- [ ]     Create a person (teacher or student, not a plain Person).
- [ ]     Create a book.
- [ ]     Create a rental.
- [ ]     List all rentals for a given person id.

-  In your ``main.rb`` define the entry point, this will be a method called main that is invoked at the end of your file. This method should do the following:

- [ ]     Present the user with a list of options to perform.
- [ ]     Lets users choose an option.
- [ ]     If needed, ask for parameters for the option.
- [ ]     Have a way to quit the app.

2023-03-10 19:48 UTC, Mihndim2020 requested changes
### Hi @belaymit, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark:  Clean and Organized code
:heavy_check_mark: Descriptive Readme file

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)

# Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 19:48 UTC, Mihndim2020 commented on main.rb
> +
- [ ] I am getting an error when I try to run your code, checkout the screenshot below and kindly fix the issue. Please make sure you app is running according to the project [requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_ui.md) before you submit for another review.  

![ruby error](https://user-images.githubusercontent.com/65852621/224413660-2ea9f723-4d0f-490e-a6d2-aa6c51624788.PNG)

2023-03-10 20:30 UTC, mckent05 requested changes
Hi @belaymit, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost there](https://user-images.githubusercontent.com/73607512/207265397-5ef597f5-a50c-49b4-8f07-7548b0520e98.gif)


 ## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your code.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-10 20:30 UTC, mckent05 commented on app.rb
> +end
- Please implement all tasks required for this [milestone] (https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_ui.md). Please implement the code required to carry out each of those tasks. Please fix this 🙏 . Currently your application only prints `display books`.

2023-03-11 08:58 UTC, frank1738 requested changes
Hi @belaymit , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>


## Highlights

✅ Correct use of Gitflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-11 08:58 UTC, frank1738 commented on src/classes/person.rb
> +  def initialize(age, name, parent_permission: true)
- [ ] Good work displaying the options, but when I try to create a person, an error occurs. Kindly check it out.

![image](https://user-images.githubusercontent.com/98453979/224475152-55657fdf-e18f-4212-a76e-9baba805ea07.png)

![image](https://user-images.githubusercontent.com/98453979/224475181-f8fc45bf-0d48-40af-a7bd-7e5cf5ca1f94.png)

2023-03-11 09:35 UTC, CollinsTatang approved these changes
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-11 09:35 UTC, merged